import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./index.css";
import Navbar from "@/components/layout/Navbar";
import { Toaster } from "sonner";
import Footer from "@/components/layout/Footer";
import { AuthProvider } from "@/utils/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning 
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <Navbar></Navbar>
          <Toaster richColors />
          <div className="my-20 min-h-[80vh]">
            {children}
          </div>
          <Footer></Footer>
        </AuthProvider>
      </body>
    </html>
  );
}
